#
#     Copyright (c) 2013 Battelle Memorial Institute
#     Licensed under modified BSD License. A copy of this license can be found
#     in the LICENSE file in the top level directory of this distribution.
#

# AMREX_HOME defines the directory in which we will find all the AMReX code
AMREX_HOME ?= ../subprojects/amrex

# TOP defines the directory in which we will find Source, Exec, etc
TOP = ..

# compilation options
COMP    = gnu
USE_MPI = TRUE
USE_OMP = FALSE

DEBUG     = FALSE
DEBUG     = TRUE

PROFILE       = FALSE
TRACE_PROFILE = FALSE
COMM_PROFILE  = FALSE
TINY_PROFILE  = FALSE

# physics
DIM      = 3

include ./Make.bmx
